import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@/components/navbar/Navbar";
import { Provider } from "@/context/Provider";
import "./globals.css";
import NoteProvider from "@/features/notes/context/NoteProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}>
        <Navbar />
        <div className="p-3">
          {/* <ThemeProvider>
            </ThemeProvider> */}
          <Provider>
            <NoteProvider>{children}</NoteProvider>
          </Provider>
        </div>
      </body>
    </html>
  );
}
